name: Image Optimization to AVIF

on:
  push:
    branches:
      - main
      - master # Added master branch for common setups
      
  # Enables manual running from the GitHub Actions tab
  workflow_dispatch:  

jobs:
  optimize_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Squoosh CLI
        run: npm install -g @squoosh/cli

      - name: Find and Optimize Images
        id: optimize
        run: |
          echo "Starting recursive search in img/ for JPEGs and PNGs..."
          
          # FIX: Simplified the find -exec structure for stability, eliminating the
          # problematic final 'sh' argument that was being interpreted as a filename.
          find img -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) -exec sh -c '
            # The file path is correctly passed as $0 (since we removed the extra 'sh' argument).
            IMG_FILE="$0"
            AVIF_FILE="${IMG_FILE%.*}.avif"
            echo "Optimizing $IMG_FILE to $AVIF_FILE"
            
            npx @squoosh/cli --avif '{"quality":75,"speed":6}' "$IMG_FILE"
            SQUOOSH_EXIT_CODE=$?
            
            if [ $SQUOOSH_EXIT_CODE -eq 0 ]; then
              rm -f "$IMG_FILE"
              echo "Converted and deleted original."
            else
              echo "ERROR: Squoosh failed to process $IMG_FILE (Exit Code: $SQUOOSH_EXIT_CODE). Keeping original."
            fi
            
          ' {} \; # CRITICAL CHANGE: Removed the extra 'sh' and now use {} directly as $0
          
          echo "Staging all changes in the working directory..."
          git add .
          
          echo "Optimization complete."
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Commit Optimized Images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto: Convert images to AVIF via GitHub Action'
          branch: main
