name: Image Optimization to AVIF

on:
  push:
    branches:
      - main
  
  # Enables manual running from the GitHub Actions tab (Run workflow button)
  workflow_dispatch: 

jobs:
  optimize_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Squoosh CLI
        run: npm install -g @squoosh/cli

      - name: Find and Optimize Images
        id: optimize
        run: |
          echo "Starting recursive search in img/ for JPEGs and PNGs..."
          
          # This command searches 'img' and ALL subdirectories for files ending in .jpg, .jpeg, or .png
          find img -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) | while read IMG_FILE; do
            echo "Optimizing found file: $IMG_FILE to AVIF..."
            
            # 1. Define the final target path for the AVIF file
            AVIF_FILE="${IMG_FILE%.*}.avif"
            
            # 2. Run Squoosh to create the new AVIF file
            # Squoosh CLI writes the output next to the input file, e.g., creates 'image.avif' next to 'image.jpg'
            npx @squoosh/cli --avif '{"quality":75,"speed":6}' "$IMG_FILE"
            
            # 3. Rename/Move the Squoosh output file to the final destination
            SQUOOSH_OUTPUT="${IMG_FILE%.*}.avif"
            mv "$SQUOOSH_OUTPUT" "$AVIF_FILE"
            
            # 4. Remove the old unoptimized file
            rm "$IMG_FILE"
            
            echo "Converted and deleted original."
          done
          echo "Optimization complete."
        env:
          # Increase memory limit for Squoosh, which can be memory-intensive
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Commit Optimized Images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto: Convert images to AVIF via GitHub Action (Recursive)'
          branch: main
          # Use recursive globbing to capture all files in the 'img' directory
          files: 'img/**/*'