name: Image Optimization to AVIF

on:
  push:
    branches:
      - main
      - master # Added master branch for common setups
      
  # Enables manual running from the GitHub Actions tab
  workflow_dispatch:  

jobs:
  optimize_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Squoosh CLI
        run: npm install -g @squoosh/cli

      - name: Find and Optimize Images
        id: optimize
        run: |
          echo "Starting recursive search in img/ for JPEGs and PNGs..."
          
          # Use find with -exec sh -c for maximum path safety (handles spaces/special chars)
          find img -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png \) -exec sh -c '
            IMG_FILE="$1"
            AVIF_FILE="${IMG_FILE%.*}.avif"
            echo "Optimizing $IMG_FILE to $AVIF_FILE"
            
            # CRITICAL FIX: Removed the problematic "-o $AVIF_FILE" flag.
            # Squoosh automatically outputs the AVIF file by replacing the extension (e.g., image.jpg -> image.avif).
            npx @squoosh/cli --avif '{"quality":75,"speed":6}' "$IMG_FILE"
            SQUOOSH_EXIT_CODE=$?
            
            if [ $SQUOOSH_EXIT_CODE -eq 0 ]; then
              # Conversion succeeded, safely remove the original file.
              rm -f "$IMG_FILE"
              echo "Converted and deleted original."
            else
              # Conversion failed. Keep the original file and log the error.
              echo "ERROR: Squoosh failed to process $IMG_FILE (Exit Code: $SQUOOSH_EXIT_CODE). Keeping original."
            fi
            
          ' sh {} \;
          
          # CRITICAL: Manually stage all changes (new AVIFs, deleted JPEGs) 
          # so the auto-commit action sees them and doesn't report a clean tree.
          echo "Staging all changes in the working directory..."
          git add .
          
          echo "Optimization complete."
        env:
          # Increase memory limit for Squoosh, which can be memory-intensive
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Commit Optimized Images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Auto: Convert images to AVIF via GitHub Action'
          branch: main
          # The files are now pre-staged by the previous step, so the commit will succeed
